"""Deterministic, provably-equivalent predicate rewrites (2026-09-17).

Why this module exists: the model proposed `SUBSTR(MANAGE_CD, 6, 3) = '551'`
→ `MANAGE_CD LIKE '__%551%'` on a production report. That is a *different*
predicate (matches 551 anywhere after the 2nd character), and nothing in
the pipeline could notice: full rewrites were checked structurally only, and
advice fragments were not checked at all. An LLM predicts plausible text; it
does not verify equivalence.

The fix is to make the *system* the authority on equivalence for the small
set of predicate patterns that are actually worth rewriting. The model may
say "this predicate can be improved"; the equivalent form is derived here,
and whatever the model wrote is either confirmed, replaced, or flagged as
unverified. Anything outside this whitelist is never presented as an
equivalent rewrite.

Every rule documents its equivalence argument and any assumption it needs.

2026-09-18 (SQLCheck Runtime Correctness v1): only rewrites whose
equivalence can be proven from the SQL text alone belong here. TRUNC(col)=X
→ range and NVL(col,'a')='b' → plain comparison were removed: the first
needs X to carry no time component (and col to be a DATE, not a NUMBER or a
time-zoned TIMESTAMP), the second needs col not to be CHAR/NCHAR
(blank-padded vs. nonpadded comparison) — none of which SQLCheck can see.
Fragments of those shapes are now "unverified", and a full rewrite that
changes them is rejected. See backend/app/knowledge/pattern_catalog.yaml.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from sqlglot import exp, parse_one
from sqlglot.optimizer.normalize_identifiers import normalize_identifiers

DIALECT = "oracle"

_WILDCARD_RE = re.compile(r"[%_]")

# Reviewer-facing rejection reasons (plain language, no "等價" jargon —
# 2026-09-17 user request): say that the query result might change.
REASON_UNVERIFIABLE_CHANGE = "建議寫法改動了條件，系統無法確認查詢結果是否相同"
REASON_MISMATCH = "建議寫法的條件改法與系統推算的結果不同，查詢結果可能改變"
REASON_ADDED_CONDITION = "建議寫法新增了條件，系統無法確認查詢結果是否相同"


@dataclass(frozen=True)
class Rewrite:
    """One derived rewrite: `canonical` is the preferred text, `accepted`
    lists every normalized form considered equivalent (canonical included),
    `assumption` is a reviewer-facing caveat when equivalence needs one."""

    rule: str
    canonical: str
    accepted: tuple[str, ...]
    assumption: str | None = None


@dataclass(frozen=True)
class FragmentVerification:
    status: str  # verified | corrected | unverified
    example: str  # what to show as the suggested fragment
    rule: str | None = None
    assumption: str | None = None


# ---------------------------------------------------------------------------
# Parsing / normalization helpers
# ---------------------------------------------------------------------------
def parse_predicate(text: str) -> exp.Expression | None:
    """Parse a bare condition fragment (`A.X = 1 AND ...`). Returns None when
    the text is not a condition (prose, a whole SELECT, garbage)."""
    if not text or not text.strip():
        return None
    try:
        tree = parse_one(f"SELECT 1 FROM DUAL WHERE {text.strip().rstrip(';')}", read=DIALECT)
    except Exception:
        return None
    if not isinstance(tree, exp.Select):
        return None
    where = tree.args.get("where")
    return where.this if where is not None else None


def normalize(expr: exp.Expression) -> str:
    """Canonical text for equality comparison: identifiers case-folded the
    Oracle way, regenerated by sqlglot so whitespace/parentheses/keyword case
    do not matter. Literal contents are untouched."""
    return normalize_identifiers(expr.copy(), dialect=DIALECT).sql(dialect=DIALECT)


def normalize_text(text: str) -> str | None:
    expr = parse_predicate(text)
    return normalize(expr) if expr is not None else None


def _conjuncts(expr: exp.Expression) -> list[exp.Expression]:
    if isinstance(expr, exp.And):
        return _conjuncts(expr.this) + _conjuncts(expr.expression)
    if isinstance(expr, exp.Paren):
        return _conjuncts(expr.this)
    return [expr]


def _is_string_literal(node: exp.Expression | None) -> bool:
    return isinstance(node, exp.Literal) and node.is_string


def _int_literal(node: exp.Expression | None) -> int | None:
    if isinstance(node, exp.Literal) and not node.is_string:
        try:
            return int(node.this)
        except ValueError:
            return None
    return None


def _column_sql(col: exp.Expression) -> str:
    return col.sql(dialect=DIALECT)


# ---------------------------------------------------------------------------
# Rules. Each takes one atom (a Predicate or an Or-chain) and returns a
# Rewrite or None. Order matters only for readability; at most one applies.
# ---------------------------------------------------------------------------
def _rule_substr_eq(pred: exp.Expression) -> Rewrite | None:
    """SUBSTR(col, p, n) = 'v'  →  col LIKE '<p-1 underscores>v%'

    Equivalence: SUBSTR yields the n characters starting at p; equality with a
    literal of length n holds iff the characters at positions p..p+n-1 are
    exactly v, which is what the LIKE pattern says (`_` = one character,
    trailing `%` = anything after). NULL col → NULL on both sides. Requires
    len(v) == n (otherwise SUBSTR can never equal v → not rewritable here)
    and v free of LIKE metacharacters. For p == 1 the pattern is 'v%'.
    Also accepted for p == 1: the prefix-bounds form
    `col >= 'v' AND col < 'next(v)'` the prompt has long taught the model."""
    if not isinstance(pred, exp.EQ):
        return None
    func, lit = pred.this, pred.expression
    if _is_string_literal(func) and isinstance(lit, exp.Func):
        func, lit = lit, func
    if not isinstance(func, exp.Substring) or not _is_string_literal(lit):
        return None
    col = func.this
    if not isinstance(col, exp.Column):
        return None
    start = _int_literal(func.args.get("start"))
    length = _int_literal(func.args.get("length"))
    value = str(lit.this)
    if start is None or start < 1 or length is None or length < 1:
        return None
    if len(value) != length or _WILDCARD_RE.search(value):
        return None
    pattern = "_" * (start - 1) + value + "%"
    canonical = f"{_column_sql(col)} LIKE '{pattern}'"
    accepted = [normalize_text(canonical) or canonical]
    if start == 1:
        nxt = _next_prefix(value)
        if nxt is not None:
            bounds = f"{_column_sql(col)} >= '{value}' AND {_column_sql(col)} < '{nxt}'"
            n = normalize_text(bounds)
            if n:
                accepted.append(n)
    return Rewrite(rule="substr_eq_to_like", canonical=canonical, accepted=tuple(accepted))


def _next_prefix(value: str) -> str | None:
    """'107' → '108', '10Z' → None (no safe successor without collation
    knowledge). Only digits and letters other than 9/z/Z are incremented."""
    last = value[-1]
    if last in "9zZ" or not last.isalnum():
        return None
    return value[:-1] + chr(ord(last) + 1)


def _rule_or_eq_to_in(atom: exp.Expression) -> Rewrite | None:
    """col = a OR col = b [OR ...]  →  col IN (a, b, ...). Exact."""
    if not isinstance(atom, exp.Or):
        return None
    disjuncts: list[exp.Expression] = []

    def flatten(e: exp.Expression) -> None:
        if isinstance(e, exp.Or):
            flatten(e.this)
            flatten(e.expression)
        elif isinstance(e, exp.Paren):
            flatten(e.this)
        else:
            disjuncts.append(e)

    flatten(atom)
    if len(disjuncts) < 2:
        return None
    col_sql: str | None = None
    values: list[str] = []
    for d in disjuncts:
        if not isinstance(d, exp.EQ) or not isinstance(d.this, exp.Column):
            return None
        if not isinstance(d.expression, (exp.Literal, exp.Placeholder, exp.Parameter)):
            return None
        this_col = normalize(d.this)
        if col_sql is None:
            col_sql = this_col
        elif this_col != col_sql:
            return None
        values.append(d.expression.sql(dialect=DIALECT))
    canonical = f"{disjuncts[0].this.sql(dialect=DIALECT)} IN ({', '.join(values)})"
    return Rewrite(rule="or_eq_to_in", canonical=canonical, accepted=(normalize_text(canonical) or canonical,))


_RULES = (_rule_substr_eq, _rule_or_eq_to_in)


def derive(atom: exp.Expression) -> Rewrite | None:
    for rule in _RULES:
        try:
            r = rule(atom)
        except Exception:
            r = None
        if r is not None:
            return r
    return None


# ---------------------------------------------------------------------------
# Public API 1: advice fragments (before → example)
# ---------------------------------------------------------------------------
def verify_fragment(before: str, example: str) -> FragmentVerification:
    """Decide what to show for one advice item's before/example pair.

    - `before` parses and a rule applies: the model's `example` is compared
      against the accepted forms → "verified" (as written) or "corrected"
      (replaced by the canonical form; the model's text was NOT equivalent).
    - Otherwise → "unverified": the fragment is shown, but labelled as a
      sketch the system could not prove equivalent.
    Multi-conjunct `before` is handled conjunct by conjunct: every conjunct
    must either be unchanged in `example` or rewritten by a rule."""
    before_expr = parse_predicate(before)
    example_norm = normalize_text(example)
    if before_expr is None:
        return FragmentVerification(status="unverified", example=example)

    canonical_parts: list[str] = []
    accepted_sets: list[tuple[str, ...]] = []
    rules: list[str] = []
    assumptions: list[str] = []
    for atom in _conjuncts(before_expr):
        rw = derive(atom)
        if rw is None:
            n = normalize(atom)
            canonical_parts.append(atom.sql(dialect=DIALECT))
            accepted_sets.append((n,))
        else:
            canonical_parts.append(rw.canonical)
            accepted_sets.append(rw.accepted)
            rules.append(rw.rule)
            if rw.assumption:
                assumptions.append(rw.assumption)
    if not rules:
        return FragmentVerification(status="unverified", example=example)

    canonical = " AND ".join(canonical_parts)
    assumption = "；".join(assumptions) or None
    rule = "+".join(rules)
    if example_norm is not None and _matches(example_norm, accepted_sets):
        return FragmentVerification(status="verified", example=example, rule=rule, assumption=assumption)
    return FragmentVerification(status="corrected", example=canonical, rule=rule, assumption=assumption)


def _matches(example_norm: str, accepted_sets: list[tuple[str, ...]]) -> bool:
    """True when the example's conjuncts are exactly one accepted form per
    original conjunct (order-insensitive)."""
    example_expr = parse_predicate(example_norm)
    if example_expr is None:
        return False
    remaining = [normalize(c) for c in _conjuncts(example_expr)]
    for accepted in accepted_sets:
        hit = None
        for form in accepted:
            form_parts = [normalize(c) for c in _conjuncts(parse_predicate(form) or exp.Null())]
            if form_parts and all(p in remaining for p in form_parts):
                hit = form_parts
                break
        if hit is None:
            return False
        for p in hit:
            remaining.remove(p)
    return not remaining


# ---------------------------------------------------------------------------
# Public API 2: full rewrite — every changed condition must be rule-derived
# ---------------------------------------------------------------------------
def _atoms(tree: exp.Expression) -> list[exp.Expression]:
    """Condition atoms of a statement: Or-chains are one atom (so OR→IN can
    be recognised), every other Predicate is one atom. Subquery contents are
    included; identical ones cancel out in the set comparison."""
    atoms: list[exp.Expression] = []

    def walk(node: exp.Expression) -> None:
        if isinstance(node, exp.Or):
            atoms.append(node)
            return
        if isinstance(node, exp.Predicate):
            atoms.append(node)
            return
        for child in node.iter_expressions():
            walk(child)

    walk(tree)
    return atoms


def verify_predicate_changes(original: exp.Expression, suggested: exp.Expression) -> tuple[bool, str | None]:
    """(ok, reason). ok only when every atom that disappeared from the
    original has a rule-derived equivalent present in the suggestion and no
    unexplained atom was added."""
    orig = {normalize(a): a for a in _atoms(original)}
    sugg = {normalize(a): a for a in _atoms(suggested)}
    removed = [a for n, a in orig.items() if n not in sugg]
    added = {n for n in sugg if n not in orig}
    for atom in removed:
        rw = derive(atom)
        if rw is None:
            return False, REASON_UNVERIFIABLE_CHANGE
        consumed = False
        for form in rw.accepted:
            parts = [normalize(c) for c in _conjuncts(parse_predicate(form) or exp.Null())]
            if parts and all(p in added or p in orig for p in parts):
                for p in parts:
                    added.discard(p)
                consumed = True
                break
        if not consumed:
            return False, REASON_MISMATCH
    if added:
        return False, REASON_ADDED_CONDITION
    return True, None
